### ISSUE TITLE
Certificates vs Key

### ISSUE THREAD

**Issue by iammattmartin** [zulip/phabricator-to-zulip#4]
Following the docs and noting #3, has anyone tried this with the current Phab versions?

We can't seem to generate the certificate length it requires and the commands for arc all seem to want a newer format which are not the length that this expects.

Fairly old code now so I suspect something may have changed but it would be good to get working as its listed as an integration from the Zulip site.

**Comment by timabbott** [comment]
Not that I'm aware of, but I generally wouldn't hear about it if it is working for folks.

If anyone who uses phabricator is up for helping maintain this project, that'd be very welcome.  Structurally, I'd be happier with adding a [Zulip webhook integration](https://zulip.com/api/incoming-webhooks-overview) for that, which Zulip as a project is setup to maintain hundreds of, and would eliminate the need for an out-of-tree PHP project.
